# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/astar.ui'
#
# Created: Mon Jan 25 15:04:20 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 500)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tblMap = QtGui.QTableWidget(self.centralwidget)
        self.tblMap.setGeometry(QtCore.QRect(10, 10, 400, 400))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblMap.sizePolicy().hasHeightForWidth())
        self.tblMap.setSizePolicy(sizePolicy)
        self.tblMap.setObjectName(_fromUtf8("tblMap"))
        self.tblMap.setColumnCount(0)
        self.tblMap.setRowCount(0)
        self.tblMap.horizontalHeader().setVisible(False)
        self.tblMap.verticalHeader().setVisible(False)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(420, 10, 371, 401))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.mainControls_vLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mainControls_vLayout.setMargin(0)
        self.mainControls_vLayout.setObjectName(_fromUtf8("mainControls_vLayout"))
        self.cellTypeControls = QtGui.QVBoxLayout()
        self.cellTypeControls.setObjectName(_fromUtf8("cellTypeControls"))
        self.cellLblLayout = QtGui.QHBoxLayout()
        self.cellLblLayout.setObjectName(_fromUtf8("cellLblLayout"))
        self.lblTypeSelect = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblTypeSelect.setObjectName(_fromUtf8("lblTypeSelect"))
        self.cellLblLayout.addWidget(self.lblTypeSelect)
        self.cellTypeControls.addLayout(self.cellLblLayout)
        self.cellBttnLayout = QtGui.QHBoxLayout()
        self.cellBttnLayout.setObjectName(_fromUtf8("cellBttnLayout"))
        self.rBttn_Start = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rBttn_Start.setChecked(True)
        self.rBttn_Start.setAutoExclusive(True)
        self.rBttn_Start.setObjectName(_fromUtf8("rBttn_Start"))
        self.CellBttnGroup = QtGui.QButtonGroup(MainWindow)
        self.CellBttnGroup.setObjectName(_fromUtf8("CellBttnGroup"))
        self.CellBttnGroup.addButton(self.rBttn_Start)
        self.cellBttnLayout.addWidget(self.rBttn_Start)
        self.rBttn_End = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rBttn_End.setAutoExclusive(True)
        self.rBttn_End.setObjectName(_fromUtf8("rBttn_End"))
        self.CellBttnGroup.addButton(self.rBttn_End)
        self.cellBttnLayout.addWidget(self.rBttn_End)
        self.rBttn_Wall = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rBttn_Wall.setAutoExclusive(True)
        self.rBttn_Wall.setObjectName(_fromUtf8("rBttn_Wall"))
        self.CellBttnGroup.addButton(self.rBttn_Wall)
        self.cellBttnLayout.addWidget(self.rBttn_Wall)
        self.cellTypeControls.addLayout(self.cellBttnLayout)
        self.mainControls_vLayout.addLayout(self.cellTypeControls)
        self.worldSizeControls = QtGui.QVBoxLayout()
        self.worldSizeControls.setObjectName(_fromUtf8("worldSizeControls"))
        self.worldLbl_hLayout = QtGui.QHBoxLayout()
        self.worldLbl_hLayout.setObjectName(_fromUtf8("worldLbl_hLayout"))
        self.lblWorldSize = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblWorldSize.setObjectName(_fromUtf8("lblWorldSize"))
        self.worldLbl_hLayout.addWidget(self.lblWorldSize)
        self.worldSizeControls.addLayout(self.worldLbl_hLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.worldSize_spinbox = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.worldSize_spinbox.setMinimum(2)
        self.worldSize_spinbox.setMaximum(100)
        self.worldSize_spinbox.setSingleStep(2)
        self.worldSize_spinbox.setProperty("value", 4)
        self.worldSize_spinbox.setObjectName(_fromUtf8("worldSize_spinbox"))
        self.horizontalLayout_6.addWidget(self.worldSize_spinbox)
        self.bttnGenerateGrid = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bttnGenerateGrid.setObjectName(_fromUtf8("bttnGenerateGrid"))
        self.horizontalLayout_6.addWidget(self.bttnGenerateGrid)
        self.worldSizeControls.addLayout(self.horizontalLayout_6)
        self.mainControls_vLayout.addLayout(self.worldSizeControls)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblAlgorithm = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblAlgorithm.setObjectName(_fromUtf8("lblAlgorithm"))
        self.horizontalLayout_7.addWidget(self.lblAlgorithm)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rBttn_Astar = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rBttn_Astar.setChecked(True)
        self.rBttn_Astar.setAutoExclusive(False)
        self.rBttn_Astar.setObjectName(_fromUtf8("rBttn_Astar"))
        self.AlgorithmBttnGroup = QtGui.QButtonGroup(MainWindow)
        self.AlgorithmBttnGroup.setObjectName(_fromUtf8("AlgorithmBttnGroup"))
        self.AlgorithmBttnGroup.addButton(self.rBttn_Astar)
        self.horizontalLayout_8.addWidget(self.rBttn_Astar)
        self.rBttn_DStar = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rBttn_DStar.setEnabled(False)
        self.rBttn_DStar.setCheckable(True)
        self.rBttn_DStar.setObjectName(_fromUtf8("rBttn_DStar"))
        self.AlgorithmBttnGroup.addButton(self.rBttn_DStar)
        self.horizontalLayout_8.addWidget(self.rBttn_DStar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.mainControls_vLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.bttnSolve = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.bttnSolve.setObjectName(_fromUtf8("bttnSolve"))
        self.horizontalLayout_9.addWidget(self.bttnSolve)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.mainControls_vLayout.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblTypeSelect.setText(_translate("MainWindow", "Cell type", None))
        self.rBttn_Start.setText(_translate("MainWindow", "Start", None))
        self.rBttn_End.setText(_translate("MainWindow", "End", None))
        self.rBttn_Wall.setText(_translate("MainWindow", "Wall", None))
        self.lblWorldSize.setText(_translate("MainWindow", "World size", None))
        self.bttnGenerateGrid.setText(_translate("MainWindow", "Generate grid", None))
        self.lblAlgorithm.setText(_translate("MainWindow", "Algorithm", None))
        self.rBttn_Astar.setText(_translate("MainWindow", "A*", None))
        self.rBttn_DStar.setText(_translate("MainWindow", "D*", None))
        self.bttnSolve.setText(_translate("MainWindow", "Solve", None))

